name: Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
	
	workflow_dispatch:
		
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Tests
        run: mvn clean test